# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://sybil63.github.com
title: Sybil's Blog
subtitle: Now is only the beginning~
author: Sybil

#The syntax to highlight code
#monokai, perldoc, default, native
syntax: monokai

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: pretty
markdown: rdiscount
pygments: true # default python pygments have been replaced by pygments.rb

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
# Github repositories
github_user: sybil63
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Disqus Comments
disqus_short_name: sybil63
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-30241835-1
